# create sample data for boston to visualize

In [1]:
import os
import pandas as pd
import numpy as np
from glob import glob
import gspread
import h3
from tqdm import tqdm
# from fcmeans import FCM
import matplotlib.pyplot as plt
from sklearn import manifold
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import NMF
from sklearn.metrics import silhouette_score, silhouette_samples
import seaborn as sns
# import kmean
from sklearn.cluster import KMeans
from scipy.spatial import distance
import os

In [8]:
# load tsne data
ROOTFOLDER = "/Users/yuan/Dropbox (Personal)/Personal Work/_Projects2023/01_city-never-was"
DATA_FOLDER = f"{ROOTFOLDER}/_data/_curated/c_seg_hex"
DATA_EXPORT = f"{ROOTFOLDER}/_data/_curated/c_hex_cluster"
if not os.path.exists(DATA_EXPORT):
    os.makedirs(DATA_EXPORT)
BOUND_FOLDER = f"{ROOTFOLDER}/_data/_raw/r_boundary_osm"

# GRAPHIC_PATH = "/group/geog_pyloo/08_GSV/_graphic/cluster/allcities"
GRAPHIC_PATH = f"{ROOTFOLDER}/_graphic/cluster_within_city"
EXPORT_FOLDER = f"{ROOTFOLDER}/_data/_curated/_export/for_concept_viz"
if not os.path.exists(GRAPHIC_PATH):
    os.makedirs(GRAPHIC_PATH)
res = 9

FILENAME = "c_seg_cat=31_res={res}_tsne.parquet"
df = pd.read_parquet(os.path.join(DATA_FOLDER, FILENAME.format(res = res)))
FILENAME_ORI = "c_seg_cat=31_res={res}.parquet"
df_ori = pd.read_parquet(os.path.join(DATA_FOLDER, FILENAME_ORI.format(res = res)))

In [17]:
city_sel = 'boston'
df = pd.read_csv(os.path.join(DATA_FOLDER, "c_seg_cat=31_res={res}_tsne_cluster={n}.csv".format(res = res, n = 8)))
df = df[df.city_lower == city_sel].reset_index(drop=True)
df.head()

,city_lower,hex_id,img_count,res,tsne_1,tsne_2,cluster_8
0,boston,892a30019c3ffff,4,9.0,0.000007,-1.067850e-07,5
1,boston,892a30019d3ffff,4,9.0,0.000009,7.774664e-06,5
2,boston,892a30019d7ffff,12,9.0,-0.000014,-1.912034e-05,3
3,boston,892a3004407ffff,8,9.0,-0.000006,-6.669562e-06,3
4,boston,892a3004413ffff,8,9.0,-0.000005,-2.526627e-05,0

In [18]:
# create hexagon geometry into geodataframe using the hex_id
from shapely.geometry import Polygon
import geopandas as gpd
gdf = df.copy()
gdf['geometry'] = gdf['hex_id'].apply(lambda x: Polygon(h3.h3_to_geo_boundary(x, geo_json=True)))
# convert to geodataframe geometry
gdf = gpd.GeoDataFrame(gdf, geometry='geometry', crs='EPSG:4326')

In [19]:
gdf.to_file(os.path.join(EXPORT_FOLDER, f"{city_sel}_hex_res{res}.geojson"), driver='GeoJSON')

In [15]:
df = pd.read_csv(os.path.join(DATA_FOLDER, "c_seg_cat=31_res={res}_tsne_cluster={n}.csv".format(res = res, n = 8)))
df = df[df.city_lower == city_sel].reset_index(drop=True)
df.head()

,city_lower,hex_id,img_count,res,tsne_1,tsne_2,cluster_8
0,boston,892a30019c3ffff,4,9.0,0.000007,-1.067850e-07,5
1,boston,892a30019d3ffff,4,9.0,0.000009,7.774664e-06,5
2,boston,892a30019d7ffff,12,9.0,-0.000014,-1.912034e-05,3
3,boston,892a3004407ffff,8,9.0,-0.000006,-6.669562e-06,3
4,boston,892a3004413ffff,8,9.0,-0.000005,-2.526627e-05,0